name:                haskell-chess
version:             0.1.0.0
github:              "ovladisluvv/Haskell-Chess-2026"
license:             BSD-3-Clause
author:              "Ogai Vladislav, Ismurzenov Abay"
maintainer:          "example@example.com"
copyright:           "Ogai Vladislav, Ismurzenov Abay"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Chess game implemented in Haskell using Gloss for rendering
# category:            Game

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/ovladisluvv/Haskell-Chess-2026#readme>

dependencies:
- base >= 4.19.0.0 && < 5
- vector
- gloss
- random

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  chess-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-chess

tests:
  chess-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-chess
